[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "myproject"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
readme = "README.md"
dependencies = [
    "biopython==1.88",
    "numpy==2.5.3",
    "tf_keras==2.21.0",  
    "torch==2.12.0",
]

[tool.setuptools.packages.find]
where = ["."]